[lint]
future-annotations = true
select = ["ALL"]
ignore = [
    "ANN", # maybe cleanup later - annotations
    "C408", # ignore - dict call
    "C901", # ignore - complex structure
    "COM812", # ignore - ruff format
    "D", # ignore - docstrings
    "E501", # ignore - line too long
    # "E741", # ignore - ambiguous variable name
    # "EM101", # ignore - string literal in exception
    # "EM102", # ignore - f-string in exception
    "N", # ignore - naming
    # "PERF203", # ignore (false positive?) - try-except in loop
    "PLC0415", # ignore - import at top-level of file
    "PLR0913", # ignore - too many arguments
    # "PLR0915", # ignore - too many statements
    "PLR2004", # ignore - magic value comparison
    "PTH", # ignore - pathlib
    "Q", # ignore - quotes style
    # "S101", # ignore - asserts
    "SLF001", # ignore - private member accessed
    "TD", # ignore - todos
    # "TRY003", # ignore - raise vanilla args
    "UP031", # maybe cleanup later - printf string formatting
]

pyupgrade.keep-runtime-typing = true


[lint.flake8-type-checking]
strict = true


[lint.isort]
case-sensitive = true
force-single-line = true
from-first = true
lines-after-imports = 2
no-sections = true
order-by-type = false


[lint.per-file-ignores]
"devpi_ldap/main.py" = [
    "T201", # ignore - print found
]
"tests/conftest.py" = [
    "INP001", # ignore - implicit namespace package
]
"tests/test_*.py" = [
    "INP001", # ignore - implicit namespace package
    "S101", # ignore - asserts
    "T201", # ignore - print found
]
